### ISSUE TITLE
Feature request: Split 1 option into 2 options

### ISSUE THREAD

**Issue by dreamcat4** [Helly1206/skin.xonfluence#10]
Hi there. Really like this skin. Found it yesterday, it's been awesome. However there is an issue for which cannot fully control the skin behaviour. There is 1 existing configuration option. But it needs to be converted into 2 options. This was not any problem in the original / official confluence skin.

The Existing Setting:

Skin Settings --> General --> Video OSD Settings

[X} Enable video codec info on pause and OSD menu

Suggestion:

Convert it into 2 independant settings:

[X} Enable video codec info on pause
[X} Enable video codec info on OSD menu

Reason:

Because it covers up the subtitles area while paused. For when the subtitles change too fast, I need to press Pause to stop the playback and finish reading the text,

Wheras if instead disabling the combined option. Then can read the subtitles above ^_^. BUT has the negative effect to the OSD menu at all other times. Which is very basic looking and not nice to hide from OSD.

OR If taking a still screenshot, while the movie is paused. The OSD is not wanted to be seen then either.

Any other times its needed by user to check the extra infos while in paused paused mode, can just bring up the OSD manually. Just pressing select button. And not be mantatory on every 'Pause'.

Many thanks for any consideration. By splitting this thing into 2 settings users can still have the same old behaviour if they wish. Its just a lot more flexible, and solves those newer ^_^ use-cases.

**Comment by Helly1206** [comment]
Hi Dreamcat,


Thanks for your remark. I stopped making changes until after holiday season. But i'll make a note of this and pick it up later on.


Thanks,

Helly.

________________________________
Van: Dreamcat4 <notifications@github.com>
Verzonden: woensdag 13 juli 2016 17:42:58
Aan: Helly1206/skin.xonfluence
Onderwerp: [Helly1206/skin.xonfluence] request: Split a combined option into 2 separate (independant) option (#10)


Hi there. Really like this skin. Found it yesterday, it's been awesome. However there is an issue for which cannot fully control the skin behaviour. There is 1 existing configuration option. But it needs to be converted into 2 options. This was not any problem in the original / official confluence skin.

The Existing Setting:

Skin Settings --> General --> Video OSD Settings

[X} Enable video codec info on pause and OSD menu

Suggestion:

Convert it into 2 independant settings:

[X} Enable video codec info on pause
[X} Enable video codec info on OSD menu

Reason:

Because it covers up the subtitles area while paused. For when the subtitles change too fast, I need to press Pause to stop the playback and finish reading the text,

Wheras if instead disabling the combined option. Then can read the subtitles above ^_^. BUT has the negative effect to the OSD menu at all other times. Which is very basic looking and not nice to hide from OSD.

OR If taking a still screenshot, while the movie is paused. The OSD is not wanted to be seen then either.

Any other times its needed by user to check the extra infos while in paused paused mode, can just bring up the OSD manually. Just pressing select button. And not be mantatory on every 'Pause'.

Many thanks for any consideration. By splitting this thing into 2 settings users can still have the same old behaviour if they wish. Its just a lot more flexible, and solves those newer ^_^ use-cases.

-

**Comment by Helly1206** [comment]
Hey,


Uploaded a new version today.


Splitted the setting for the Krypton version.


Decided that I won't fix on Jarvis, because it is quite a lot of work to let everything work correctly with those settings. I only do bugfixes on jarvis. Hope you don't mind about that.


Thanks,

Helly.

________________________________
Van: Dreamcat4 <notifications@github.com>
Verzonden: woensdag 13 juli 2016 17:42:58
Aan: Helly1206/skin.xonfluence
Onderwerp: [Helly1206/skin.xonfluence] request: Split a combined option into 2 separate (independant) option (#10)


Hi there. Really like this skin. Found it yesterday, it's been awesome. However there is an issue for which cannot fully control the skin behaviour. There is 1 existing configuration option. But it needs to be converted into 2 options. This was not any problem in the original / official confluence skin.

The Existing Setting:

Skin Settings --> General --> Video OSD Settings

[X} Enable video codec info on pause and OSD menu

Suggestion:

Convert it into 2 independant settings:

[X} Enable video codec info on pause
[X} Enable video codec info on OSD menu

Reason:

Because it covers up the subtitles area while paused. For when the subtitles change too fast, I need to press Pause to stop the playback and finish reading the text,

Wheras if instead disabling the combined option. Then can read the subtitles above ^_^. BUT has the negative effect to the OSD menu at all other times. Which is very basic looking and not nice to hide from OSD.

OR If taking a still screenshot, while the movie is paused. The OSD is not wanted to be seen then either.

Any other times its needed by user to check the extra infos while in paused paused mode, can just bring up the OSD manually. Just pressing select button. And not be mantatory on every 'Pause'.

Many thanks for any consideration. By splitting this thing into 2 settings users can still have the same old behaviour if they wish. Its just a lot more flexible, and solves those newer ^_^ use-cases.

-

**Comment by dreamcat4** [comment]
Oh hi okay there thanks for letting me know! Actually I might be stuck on Jarvis for a while longer but heh - it'll trickle down to me and everybody else eventually.

Many thanks for adding this.
