### ISSUE TITLE
video artifact

### ISSUE THREAD

**Issue by MarniC00** [Helly1206/skin.xonfluence#13]
Hi Helly,
Thanks for updating the skin for Krypton. I've noticed some strange artifact on video. It appears on every addon I use and it looks like this:
![1](https://cloud.githubusercontent.com/assets/19635785/19016848/04478596-881e-11e6-9b66-4353d85fd2a6.png)
![2](https://cloud.githubusercontent.com/assets/19635785/19016849/04479f90-881e-11e6-9681-2838ad2df32c.png)
Do you have an idea what may cause this issue?

**Comment by Helly1206** [comment]
Hi,


Thanks for the E-mail. I already noticed. Will be fixed in the next release.


Helly.

________________________________
Van: MarniC00 <notifications@github.com>
Verzonden: zaterdag 1 oktober 2016 22:30:02
Aan: Helly1206/skin.xonfluence
Onderwerp: [Helly1206/skin.xonfluence] video artifact (#13)


Hi Helly,
Thanks for updating the skin for Krypton. I've noticed some strange artifact on video. It appears on every addon I use and it looks like this:
[1]<https://cloud.githubusercontent.com/assets/19635785/19016848/04478596-881e-11e6-9b66-4353d85fd2a6.png>
[2]<https://cloud.githubusercontent.com/assets/19635785/19016849/04479f90-881e-11e6-9681-2838ad2df32c.png>
Do you have an idea what may cause this issue?

-

**Comment by MarniC00** [comment]
Great to hear it. There is one more issue I've noticed. Kodi crashes when I try to view any addon's changelog. Are you also aware of that?

**Comment by Helly1206** [comment]
Changelog is not supported by Kodi (krypton) anymore. It's replaced by "what's new". I removed it from the latest update.


I can't help it. It's a kodi decision.


Thanks,

helly.

________________________________
Van: MarniC00 <notifications@github.com>
Verzonden: zondag 2 oktober 2016 22:30:09
Aan: Helly1206/skin.xonfluence
CC: Ivo Helwegen; Comment
Onderwerp: Re: [Helly1206/skin.xonfluence] video artifact (#13)


Great to hear it. There is one more issue I've noticed. Kodi crashes when I try to view any addon's changelog. Are you also aware of that?

-

**Comment by gzenio22** [comment]
Hi guys, 

Now, when I updated xonfluence skin under Kodi 17 to v3.3.5 the problem still exists.
Every shortcut is gone and skin looks kind of empty...
Please see attached pic to see what I mean.
Please


![screenshot 2016-10-03 11-31-49](https://cloud.githubusercontent.com/assets/21177361/19033795/9696b28a-8960-11e6-8d35-3ea70e21b7af.jpg)

**Comment by war59312** [comment]
@gzenio22 Same issue here, on Kodi v17 “Krypton” Beta 2.

**Comment by Helly1206** [comment]
Hi Will, Gzenio22,


The issue has to do with the wraps around main menu. For the moment you can select this, I will update the skin to get rid of this bug next weekend.


Thanks,

Helly.


DJxROM Wrote:  <http://forum.kodi.tv/showthread.php?pid=2428653#pid2428653> I recently installed Krypton beta 2 and installed Xonfluence. I too was left with a empty menubar. I fixed it by going to General settings > Home Screen Options > Enable wrap around menu. It is off by default so enable it and you should be able to see the menubar.

________________________________
Van: Will <notifications@github.com>
Verzonden: maandag 3 oktober 2016 18:30:39
Aan: Helly1206/skin.xonfluence
CC: Ivo Helwegen; Comment
Onderwerp: Re: [Helly1206/skin.xonfluence] video artifact (#13)


@gzenio22<https://github.com/gzenio22> Same issue here, on Kodi v17 "Krypton" Beta 2.

-

**Comment by Helly1206** [comment]
Fixed in 3.3.6
