### ISSUE TITLE
Xonfluence for Kodi 18

### ISSUE THREAD

**Issue by TheFeliks** [Helly1206/skin.xonfluence#22]
Hi all guys and girls. Happy New Year to you all!

I am still having troubles to get use to the layout of the Kodi 17 so I've been using Xonfluence skin since K17 launch. Now, having K18 on a horizon is there a change that it will work there too?
I know this is still in Alpha version but sooner or later it will be stable as we have 2018 :)

Xonfluence gives much more possibilities than a normal Confluence and it makes all sense... not like the new layout from K17 ;)

**Comment by Helly1206** [comment]
Hi,

There will surely be a version for kodi 18. It will be released around the release of Kodi 18. I will start developing when beta versions of kodi 18 are available. Kodi 18 is still in alpha release and too subject to changes to already start developing.

Helly.
________________________________
Van: TheFeliks <notifications@github.com>
Verzonden: zaterdag 6 januari 2018 12:36
Aan: Helly1206/skin.xonfluence
CC: Subscribed
Onderwerp: [Helly1206/skin.xonfluence] Xonfluence for Kodi 18 (#22)


Hi all guys and girls. Happy New Year to you all!

I am still having troubles to get use to the layout of the Kodi 17 so I've been using Xonfluence skin since K17 launch. Now, having K18 on a horizon is there a change that it will work there too?
I know this is still in Alpha version but sooner or later it will be stable as we have 2018 :)

Xonfluence gives much more possibilities than a normal Confluence and it makes all sense... not like the new layout from K17 ;)

**Comment by TheFeliks** [comment]
I see... As I remember with Kodi 17 there were some issues at the beginning too so waiting at least for Beta is a good idea.

**Comment by kiotronic** [comment]
for me, its a good idea too, than you wait till Kodi 18 Beta... I love Xonfluence... for me, its the best skin ever...

**Comment by godoll** [comment]
Re: https://kodi.tv/article/kodi-v18-leia-story-so-far the Kodi team is starting to 'advertise' it: "... Should you wish to give it a try a new version is readily available each day. We can certainly recommend trying it out however take in mind that it’s not fully production and living room ready yet (take a backup). So far a guestimate of several hundreds of thousands users already use it so it can’t be that bad can it. ..."

But for me it's a chicken and egg problem, because I don't give it a try without Xonfluence ;-)

**Comment by h45rd** [comment]
I concur. Tried it without Xonfluence and while some of the under the hood improvements are great, I could not find any GUI I liked nearly as much as Xonfluence :)

I might not be the best metric, though. Could e.g. never fathom what made the devs move to Estuary..
Anyways.. looking forward to testing Xonfluence on Leia when the time comes.

**Comment by Helly1206** [comment]
This first release for Leia is already on github and in the repo. This version 3.4.0 doesn't have a lot of new features, but is only an update to make the skin working with Leia.

For Leia Xonfleunce will have a major update which may be released in a few weeks time (Xonfluence version 4.0.0). With new features and a major cleanup.

Helly.

**Comment by capdood** [comment]
I have an issue which I'm told is related to XONFLUENCE in Leia (only).  

When searching for movies... it will appear that the search has ended -- the search looks like it failed and the dialog box has disappeared -- and yet it continues in the background, sometimes for up to five minutes, long after I have left the addon originally used.  

All of a sudden, a link to a search long since past will try to connect and play.  This never happened in any other version of KODI.  Is this familiar?  Does it make sense?  Sounds like a bug.  I just LOVE XONFLUENCE and would hate to lose it.
