### ISSUE TITLE
Home menu items won't change language

### ISSUE THREAD

**Issue by Sopor-** [Helly1206/skin.xonfluence#34]
When changing language the home menu items will continue to use the same language it was when i installed your skin. If nothing has been changed in the home menu items could it be possible to detect this and change language on the home menu items too when changing language? I understand that these can be changed by the user so it is possible to use customize home menu items, but maybe add an option in the home menu settings to set the home menu items to the same language i'm running without force me to do a total skin reset :(

**Comment by Helly1206** [comment]
That's correct. the menu items won't change language. This is because they are hard coded as a setting. You can change the title yourself in any title (user friendly name). I cannot run a translation program in the skin when you change language, so there is nothing I can do about it. Except for making it not customizable anymore.
